version: "3.7"                    

services:                         
  xtlab-mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: sqlserver-nguyenhuduc
    restart: always
    hostname: mssql
    environment: 
      SA_PASSWORD: nguyenhuuduc123 #Thiết lập password
      ACCEPT_EULA: 'Y'
      # Express: 

    volumes:
      - mssqlvolume:/var/opt/mssql1/data # thư mục lưu DB
    #  - ./bk:/var/opt/mssql/backup
    ports:
      - "80:80"     
                        
volumes:                                
    mssqlvolume:        
      name: sqlserver-xtlab-v2